spring:
  config:
    location: local
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/survey?autoReconnect=true
#    username: dev_survey
#    password: devsurvey12345
#  jpa:
#    hibernate:
#      ddl-auto: validate
#    generate-ddl: false
#    show-sql: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/local
logging:
  config: classpath:log/log4j2-local.yml
